Task dev 1
vladimir1203/TAT_2018.2 pull request #1
Opened 2018-10-17 20:06 UTC by vladimir1203

2018-10-18 10:00 UTC, IgorKheidorov requested changes

2018-10-18 10:00 UTC, IgorKheidorov commented on DEV-1/ArgsToString.cs
> +{
Comment according to code style

2018-10-18 10:00 UTC, IgorKheidorov commented on DEV-1/ArgsToString.cs
> +        {
Good

2018-10-18 10:00 UTC, IgorKheidorov commented on DEV-1/ArgsToString.cs
> +        /// </summary>
Not necessary class in argument is in ""

2018-10-18 10:00 UTC, IgorKheidorov commented on DEV-1/Program.cs
> +using System.Linq;
Not used using

2018-10-18 10:00 UTC, IgorKheidorov commented on DEV-1/Program.cs
> +			{
Bad name for variable, better maximumUniqueCharsCount

2018-10-18 18:42 UTC, vladimir1203 commented on DEV-1/Program.cs
> +using System.Linq;
we need System.Linq; for convert from 'char' to 'string'	 in line 40

2018-10-23 11:02 UTC, IgorKheidorov approved these changes

2018-10-23 11:05 UTC, merged